apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-proxy-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-proxy
  template:
    metadata:
      labels:
        app: es-proxy
    spec:
      containers:
        - name: es-proxy
          image: faheem222/es-proxy
          envFrom:
            - secretRef:
                name: infisical-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: es-proxy-srv
spec:
  selector:
    app: es-proxy
  ports:
    - name: es-proxy
      protocol: TCP
      port: 3000
      targetPort: 3000
