apiVersion: v1
kind: Service
metadata:
  name: mongo-srv
spec:
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo-ss
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-ss
spec:
  selector:
    matchLabels:
      app: mongo-ss
  serviceName: "mongo-srv"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo-ss
    spec:
      containers:
        - name: mongo-ss
          image: mongo
          env:
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: init-script
          configMap:
            name: pg-init-script
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
