apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill
  template:
    metadata:
      labels:
        app: skill
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command:
            [
              "sh",
              "-c",
              "timeout 60 sh -c 'until nc -z mongo-srv 27017; do echo waiting for db; sleep 2; done'",
            ]
      containers:
        - name: skill
          image: faheem222/skill
          envFrom:
            - secretRef:
                name: infisical-secrets
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: my-rabbit-default-user # created by operator
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbit-default-user # created by operator
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: skill-srv
spec:
  selector:
    app: skill
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
