apiVersion: batch/v1
kind: Job
metadata:
  name: skill-seed
spec:
  template:
    spec:
      containers:
        - name: seed-skill-job
          image: faheem222/skill
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: infisical-secrets
          command: ["/bin/bash", "./scripts/seed-skill-docker-entrypoint.sh"]
      restartPolicy: Never
  backoffLimit: 2
