apiVersion: batch/v1
kind: Job
metadata:
  name: skill-seed
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command:
            [
              "sh",
              "-c",
              "timeout 60 sh -c 'until nc -z mongo-srv 27017; do echo waiting for db; sleep 2; done'",
            ]
      containers:
        - name: seed-skill-job
          image: faheem222/skill
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: infisical-secrets
          command: ["/bin/bash", "./scripts/seed-skill-docker-entrypoint.sh"]
      restartPolicy: Never
  backoffLimit: 2
